# 后端端口号
server:
  port: 8081
# 日期类型Json返回格式化
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 静态资源访问路径
  mvc:
    static-path-pattern: /wx/storage/fetch/**
  # 静态资源存储路径
  resources:
    static-locations: classpath:/static/storage/
  servlet:
    multipart:
      enabled: true
# TypeHandler扫描包
mybatis:
  type-handlers-package: com.spring.handler
# 分页插件
pagehelper:
  helper-dialect: mysql
# 日志配置
logging:
  level:
    com.spring.mapper: debug
